### ISSUE TITLE
fix the "more" item on the main menu

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#113]
it drops down to the second line when you manually adjust the size of the browser window.

**Comment by budparr** [comment]
Working on the menu and search. I'm thinking we should give the menu some logic. Essentially, the basics (hours/about), followed by events and blog, with Kidsmith too, because it has blog posts/events, and the shop, which would encompass any other shop/section pages, since those pages are mostly informational. We can also promote gift cards in other ways besides the menu.

Let me know what you think.

(this table won't look right unless you view it on Github)

| Hours/Location | About | Events | Blog | Kidsmith | Shop^ |
-----------------------|----------|----------|--------|------------|----------|
||||||Giftsmith|
||||||Gift Cards|
||||||Used Book Cellar|

**Comment by shuchibooksmith** [comment]
Hm. Well Giftsmith absolutely has to be listed in the main menu. That isn't up for debate, unfortunately.
I like the shop as a drop down menu though, with the gift cards listed. what do you think of "about" falling under Hours/Location? Or do we want to minimize the number of drop down menus?

**Comment by budparr** [comment]
Okay, thanks @shuchibooksmith - I'll think of something else (only makes sense if the shop pages are under shop).

**Comment by budparr** [comment]
@shuchibooksmith I'm nearly ready to show you something on the new navigation. A bit more tweaking, particularly on mobile. I'll keep you posted.

**Comment by shuchibooksmith** [comment]
excellent @budparr! looking forward to it!

**Comment by budparr** [comment]
Hi @shuchibooksmith 

Here's what I'm trying to accomplish:

- Give the menu some breathing room
- Remove the "more" drop-down altogether, as I don't think it serves our audience well to make them have to look for things
- Separate some of the more practical items (hours/location, buy a gift card, etc) from the main menu.
- I felt having the menu overlay the image could be confusing for some and put too much emphasis on image, and not enough on brand identity, so I changed that. The images are now smaller and abstracted.
- I felt the search our shop was rather gargantuan, so I put it up higher (right now it's a dummy link). I have a feeling folks internally aren't going to like that, but lets think it through together.

Right now this needs some tweaking on smaller screens, so try to look at it on the largest screen you can. I'm attaching a screenshot so we're on the same page.

Also note, some of the banner images may need to be revisited. I put in some code to give them the 'parallax' effect (makes them fixed to the background while the page moves around them) and that changes them a bit.

<img width="1440" alt="screen shot 2016-01-29 at 9 17 28 am" src="https://cloud.githubusercontent.com/assets/115347/12677757/2e8ab30e-c669-11e5-92ee-a3a4990d7d0f.png">

---
**Here's a link to the latest version: http://bbsv32.surge.sh/**

**Comment by shuchibooksmith** [comment]
oh! i actually really really like it! though i do think that the 'search our online shop page' needs to go directly the ABA search page or another page and not the giftcard page. i did like having a search bar up there too. @peterbooksmith what do you think??

**Comment by budparr** [comment]
The link is just a dummy link, so it would go to the right place

**Comment by peterbooksmith** [comment]
Dana happened to be close by so I showed her both versions side-by-side.  In general, she prefers the current version, mainly feels the type is easier to read, even with the photo as the background.  She also likes the photo as the background better, compared to the white background for the menu.

Personally, I fall in between.  I see your reasoning on all these things, Bud, though to my eye, I like having the photo as the background better as well.  I would be a bit concerned that the "gift cards" and "online shop" would be smaller and harder to see for some people.  One of our biggest errors (mine and Lisa's) was not making sure that stuff was present and visible when we first went live, so I don't think they should be made changed too much.  I also agree with Shuchi that it is good to have a search bar on the home page.

One smaller possible option for that - instead of saying "Search Shop" in the white search bar, and then "Search on Online Shop" right below (despite its size I find I kind of like the red button), what if we said "title, author, keyword" in the white search bar?

Could we just keep this alternate version on hold for right now?  We have a meeting with Marshall next week and we're going to look at the website together, get his feelings on everything.  I can show them this option too.  As Dana & Marshall have both told me, just because one of them doesn't like something doesn't mean we have to change it, but we do need to hear them, and I would like to do that first.

**Comment by budparr** [comment]
No problem, on waiting. Keep in mind that when I said "breathing room" I was referring to the fact that the menu, as it stands right now, has one too many items in it (it pushes the last item down on some screens). I don't think it's a good idea to stuff things in the "more" drop-down, but at the same time I want to give you space to have the pages there you feel are important - so this was my reimagining the navigation to accommodate that. 

I also feel that the images there can be very busy and that will indeed decrease your user's ability to easily navigate the site (the motto in web design is "don't make them have to think" ). I'm quite happy to wait and hear all thoughts and ideas and adjust as needed, but none of the changes are without thought, so please consider the implications carefully.

**Comment by budparr** [comment]
p.s. @peterbooksmith just as a matter of process, so you know. It's my job to come up with ideas and defend them. Just don't want you to think I'm being argumentative. It's also a perfectly fine outcome to say that the new version doesn't work for you, and to tell me to come up with something better! Have a great weekend.

**Comment by shuchibooksmith** [comment]
I happened to be on Grub Street's website, and I actually like their take on what I think Bud is trying to achieve. One of the things that Dana had an issue with was all the contrast. Not something I had initially noticed, but after she pointed it out, I did realize that there's an awful lot of white space. Grub Street's using a similar nav bar as you're suggesting, @budparr, but the photo is a lot larger. 
![image](https://cloud.githubusercontent.com/assets/15218891/12698845/04a6dd2a-c776-11e5-9174-7879ab16e53e.png)
I know we're waiting until after we meet with Dana and Marshall, just want to throw this out as something to keep in the bag of ideas as we're discussing this.

**Comment by shuchibooksmith** [comment]
ha, didn't mean to leave the "print screen on macs" search tab open! clearly, working from my computer at home. :)

**Comment by peterbooksmith** [comment]
Hi Bud - please don't change your process or stop sending ideas our way.  We definitely still want that, and I don't want to do anything to that process.  On these particular issues, I do see where you're coming from and why. Shuchi (especially) and I will keep sharing your ideas with the rest of the decision-makers here and provide feedback.  I should have a better idea of what Dana, Lisa and Marshall are thinking later this week.

**Comment by budparr** [comment]
Hey, @shuchibooksmith a little primer on whitespace https://boagworld.com/design/why-whitespace-matters/

**Comment by budparr** [comment]
Hi @shuchibooksmith and @peterbooksmith just checking on where we stand on this design iteration.
Thanks!
Bud

**Comment by peterbooksmith** [comment]
Hi @budparr - we've had a couple of discussions about this in the past week and we (Dana, Lisa, Marshall & me) still like the existing design.  I understand and explained your reasoning, we still just like the way the current version looks to our eyes.

For now, could you table that idea?  Shuchi is going to share some other things we want to work on (she will be here shortly), and we would like to deal with those first.  I realize this could make for more work later on if we change on minds on the menu at some point, but this is the best explanation I can offer right now.

Peter

**Comment by budparr** [comment]
Very well. Thanks, @peterbooksmith
