### ISSUE TITLE
Add store image with map to the Homepage Carousel

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#15]
Can we include a storefront photo with the map slide on the carousel? So it would look something like the trio of images on the righthand side of this page?
https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=avid%20bookshop

**Comment by budparr** [comment]
Once we get things going we can do anything with a slide (it's just an image or text), so yes.

**Comment by budparr** [comment]
Note that I changed the title of the issue to be a bit more specific/action-oriented.

**Comment by shuchibooksmith** [comment]
![storefrontsquare-1](https://cloud.githubusercontent.com/assets/15218891/10705963/2a6b8a42-79b0-11e5-8bfe-77e1cdaa9d8d.JPG)

**Comment by shuchibooksmith** [comment]
Instead of the Google map in the carousel, can we just use this image?

**Comment by budparr** [comment]
No problem - but the point of the map was to make it very clear to people to click on that for hours/directions. Wouldn't it better if we just made the map nicer looking?

Just to note, to me content and design are completely separate things (particularly since content can be replaced easily), so I do stuff like this at the last.

**Comment by shuchibooksmith** [comment]
Gotcha! And you might be right about map vs photo-  happy to wait until the end to sort this out!
