### ISSUE TITLE
Featured events 

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#152]
Hi, Bud!
Long time no talk!! Hope all is well. 
We have an event coming up with Chuck Pahalniuk and we're mostly handling the sales for it online through eventbrite. Because that's the only way to purchase tickets, and he's got a HUGE fanbase, I'm wondering if there's a way we can feature these kinds of events more prominently so that folks can find it easily online?
For now we're pinning a blog post to the top as a temporary solution, but would like to find a more permanent one.
Thanks!

**Comment by budparr** [comment]
Noted. I'm currently working on a new layout for the home page, so I'll incorporate this into that work.

**Comment by peterbooksmith** [comment]
@budparr since you mention a new home page layout, I should ask, have you or anyone on our end thought about having a link to the signed first editions page on the home page, once we launch?  I know it can definitely be another item in the top/drop-down menu, but I would not be surprised if Tim and others would like to see more visible than that, at least initially upon launch.  I will discuss with those involved here, but thought I should mention it, because I don't remember it coming up.

**Comment by budparr** [comment]
Yes. Well, one of the things I need to address with a new layout (and, if you recall, that last attempt a while back was trying to do this too) is that there are a lot of items on the menu, all of them "equally" important, which is not ideal.

**Comment by peterbooksmith** [comment]
Very true.  Let me see if I can find out what could be most important to the most people.
