### ISSUE TITLE
Way to paste HTML into post direct

### ISSUE THREAD

**Issue by zchyde** [sonnetmedia/brooklinebooksmith.com#157]
Bud I'm pasting an email I just recieved from one of our bloggers:

"I am wondering if there is a way to paste HTML formatted text directly into a blog post, if that makes sense.

I would love it if I could highlight and copy bmail text from Constant Contact, paste it into the blog template, and keep all of the embedded links as I do it. As it is I have to go back and copy/paste each link into the blog post. It's an annoyance only because bmail can be really heavy on links, but also its obviously not a huge deal. Just wondering if it is possible to add the feature, or if it might already be there and I'm just missing it? " 

BMail, just to remind you, is our e-newsletter that Paul creates using a Constant Contact theme. As far as I know there's currently no way to write in html in the wysiwyg, is that right?

**Comment by budparr** [comment]
did you try it?

**Comment by zchyde** [comment]
NOPE! Why would I do an insane thing like that

(trying now)

**Comment by budparr** [comment]
this might just work, but it won't be clean.

**Comment by zchyde** [comment]
http://www.brooklinebooksmith.com/2016/06/15/open-doors-always/ ok it appears to have not worked, I can now confirm that

**Comment by budparr** [comment]
Send me what you want to paste in and I'll see what I can figure out.
![](https://link.nylas.com/open/eekwpji0x2ie8fu5fvyj5z4c/local-
5276c396-ccd0?r=cmVwbHkrMDAwMWMyOTM0NzBjOTIwMGZlOGQ1ZjQzMGE0ZDU2ZDg2NTA0OWE2ZDhkN2NkODZlOTJjZjAwMDAwMDAxMTM3OTczNjM5MmExNjljZTA5OTExZjZkQHJlcGx5LmdpdGh1Yi5jb20=)

On Jun 15 2016, at 3:49 pm, Zoe &lt;notifications@github.com&gt; wrote:  

> [http://www.brooklinebooksmith.com/2016/06/15/open-doors-
always/](http://www.brooklinebooksmith.com/2016/06/15/open-doors-
always/&r=cmVwbHkrMDAwMWMyOTM0NzBjOTIwMGZlOGQ1ZjQzMGE0ZDU2ZDg2NTA0OWE2ZDhkN2NkODZlOTJjZjAwMDAwMDAxMTM3OTczNjM5MmExNjljZTA5OTExZjZkQHJlcGx5LmdpdGh1Yi5jb20=)
ok it appears to have not worked, I can now confirm that

>

> —  
> You are receiving this because you commented.  
> Reply to this email directly, [view it on
GitHub](https://github.com/sonnetmedia/brooklinebooksmith.com/issues/157#issuecomment-226299738&r=cmVwbHkrMDAwMWMyOTM0NzBjOTIwMGZlOGQ1ZjQzMGE0ZDU2ZDg2NTA0OWE2ZDhkN2NkODZlOTJjZjAwMDAwMDAxMTM3OTczNjM5MmExNjljZTA5OTExZjZkQHJlcGx5LmdpdGh1Yi5jb20=),
or [mute the
thread](https://github.com/notifications/unsubscribe/AAHCkzmpmd7hnn_ZjS4TtS33x3zVpPYrks5qMFdjgaJpZM4I2tz2&r=cmVwbHkrMDAwMWMyOTM0NzBjOTIwMGZlOGQ1ZjQzMGE0ZDU2ZDg2NTA0OWE2ZDhkN2NkODZlOTJjZjAwMDAwMDAxMTM3OTczNjM5MmExNjljZTA5OTExZjZkQHJlcGx5LmdpdGh1Yi5jb20=).![](https://github.com/notifications/beacon
/AAHCk0tHGrLIwGWOGyZ-dIrpTv90jJcbks5qMFdjgaJpZM4I2tz2.gif)

**Comment by zchyde** [comment]
This is the link - 

https://www.bostonglobe.com/lifestyle/style/2016/06/15/our-own-private-orlando/QilPzYWFh1xHq91OnoFn1L/story.html

This is the post area that should be linked, in bold - 

 Here's Lin-Manuel Miranda's supremely moving moment at the Tony Awards, a fearfully powerful **response from our community**, and a message of hope from the Dalai Lama. 

thank you!

**Comment by budparr** [comment]
one thing. what I meant was not to post the HTML, but post the rendered HTML (that is, what you see).

**Comment by zchyde** [comment]
Im not sure I know what you mean, I'm so sorry. Just copying and posting the direct text from out bmail doesn't appear to work, I assume thats not what you meant?

**Comment by budparr** [comment]
Yeah, that's what I meant. I thought it would work, but you're right, it doesn't. That tends to, even on editors where it ostensibly works, creates a mess of html.

**Comment by budparr** [comment]
Hey, @zchyde - I was just thinking about this. If the pasting the newsletter over to the blog is an ongoing thing, how about creating the newsletter on this side, as part of the site, creating an archive. Just a thought. 

Aside from this, any other issues with the editor?

**Comment by zchyde** [comment]
No issues with the editor that I can think of. I think that could be interesting, I think predominantly Paul is just copying and pasting the text and one image from the newsletter. There is more to it, "books of the month" and things like that. I know for a fact that the Powers That Be on our end are big fans of the e-newsletter form, we changed the format when the new website launched and we cut down the newsletter a lot, but it still wasn't as much as I suggested. Which is fine, I think anyone who is opening the bmail probably knows what they're getting by now. 

I think an archive could be interesting, but I think that the really pertinant, archive-able content IS what Paul is copying and pasting into the posts, so its kind of taking care of itself at this point. Early on we talked about tagging posts so people could "see more like this", I think something like that here could be useful to generate a list of only Paul's bmail posts, but its by no means top priority.

**Comment by budparr** [comment]
Okay. I've been thinking about your workflow and would like to help make it as smooth as possible. Our editor has a few limitations (but for very good reasons, which I should fully articulate to you at some point), and I want to make sure that we find a good balance.

**Comment by zchyde** [comment]
As always fully interested to hear whatever you want to teach me. The main thing that bugs me is still image compression, mostly going through and finding the image bloggers have uploaded, saving, compressing, deleting their copy, uploading mine. But I could also structure how they're uploading their photos differently to make my life more easier but I've yet to impliment it.

**Comment by budparr** [comment]
Okay, I'll take that into consideration. Are you doing that locally, or through the editor?

**Comment by zchyde** [comment]
everything happens through the editor so they can get positioning and layout the way they want it. To compress I use compressor.io . I was thinking that to make my life easier I could have everyone upload their images to a specific folder, or to the area that pops up when you open the upload box - that way, they're easier to track down and eliminate, then I could upload my files alone into the "uploads" folder. But I have yet to ask anyone to do that, since we only just started blogging and I made a big "how to blog" packet when we started this, I'm not sure I want to change how they're doing things just yet, especially if I'm not really sure it'll be THAT much more helpful. But I could do that.

**Comment by budparr** [comment]
Funny. I just recently cropped and compressed and moved (out of the root
folder, into uploads) a whole bunch of images. Didn't know you were intending
to do so.![](https://link.nylas.com/open/eekwpji0x2ie8fu5fvyj5z4c/local-
e04fa71e-
4c1a?r=cmVwbHkrMDAwMWMyOTNkNmI5MGJlNDg0ODgzNzNiY2UyM2Y1MWFmZWM0MDBhZGJmMTU0MTk1OTJjZjAwMDAwMDAxMTM3YzIwMmU5MmExNjljZTA5OTExZjZkQHJlcGx5LmdpdGh1Yi5jb20=)

On Jun 17 2016, at 4:31 pm, Zoe &lt;notifications@github.com&gt; wrote:  

> everything happens through the editor so they can get positioning and layout
the way they want it. To compress I use compressor.io . I was thinking that to
make my life easier I could have everyone upload their images to a specific
folder, or to the area that pops up when you open the upload box - that way,
they're easier to track down and eliminate, then I could upload my files alone
into the "uploads" folder. But I have yet to ask anyone to do that, since we
only just started blogging and I made a big "how to blog" packet when we
started this, I'm not sure I want to change how they're doing things just yet,
especially if I'm not really sure it'll be THAT much more helpful. But I could
do that.

>

> —  
> You are receiving this because you modified the open/close state.  
> Reply to this email directly, [view it on
GitHub](https://github.com/sonnetmedia/brooklinebooksmith.com/issues/157#issuecomment-226874205&r=cmVwbHkrMDAwMWMyOTNkNmI5MGJlNDg0ODgzNzNiY2UyM2Y1MWFmZWM0MDBhZGJmMTU0MTk1OTJjZjAwMDAwMDAxMTM3YzIwMmU5MmExNjljZTA5OTExZjZkQHJlcGx5LmdpdGh1Yi5jb20=),
or [mute the
thread](https://github.com/notifications/unsubscribe/AAHCkx0vzLJM0VngiAZWPyCbEo4nkYxMks5qMwQugaJpZM4I2tz2&r=cmVwbHkrMDAwMWMyOTNkNmI5MGJlNDg0ODgzNzNiY2UyM2Y1MWFmZWM0MDBhZGJmMTU0MTk1OTJjZjAwMDAwMDAxMTM3YzIwMmU5MmExNjljZTA5OTExZjZkQHJlcGx5LmdpdGh1Yi5jb20=).![](https://github.com/notifications/beacon
/AAHCk7N5BuaxvetmbfBVDI-9DeH2ByUsks5qMwQugaJpZM4I2tz2.gif)

**Comment by zchyde** [comment]
Ha! I have been concerned (maybe curious is the better word) about moving the images, I wasn't sure if the CMS would let me do that - I know when you do that in an ftp folder, obviously, that changes every image link you have existing. I'm also curious - what happens when we run out of space? How do we cull the images, if at all?

**Comment by budparr** [comment]
Everything is text, so it's easy to move them. I just copied the images over (after cropping/compressing) to the uploads folder and then changed the path in the posts files. 

So, in the CMS, it's a field for uploading an image, but behind that it's merely a text file, so I go through and changed:
```featured_image_path: /image_name.jpg```
to
```featured_image_path: /uploads/image_name.jpg```

I used regex to do it en masse, but doesn't have to be that way because it's just text.

As far as images, I wouldn't worry about that. You do go through a lot of images (and probably wouldn't hurt to try and reuse some of them), but shouldn't be an issue.
