### ISSUE TITLE
New Releases

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#21]
One of the carousel cards will always be New Releases, which will be a selection of our favorite new releases for the week. It would actually go to a page that is very simple. Essentially a carousel of book covers like this:

![newreleases](https://cloud.githubusercontent.com/assets/15218891/10804340/562d3c66-7d9d-11e5-909e-bfc72ae0d5dd.png)

Customers can then click on a title and it will take them to the ABA shopping cart.

These new releases would always be one of the cards in the carousel on the homepage. The card would allow for six new titles.

**Comment by budparr** [comment]
This is a bit of a joke, so don't be offended: http://shouldiuseacarousel.com/

**Comment by shuchibooksmith** [comment]
hahhahahahhaha
amazing.
not offended. i will share freely when people ask about carousels. and defer to you on this. 

do you have any thoughts for an alternative though? the new releases is something we want to feature or at least we have been featuring in bmail and want to continue to feature.

**Comment by budparr** [comment]
Well the way that I designed the carousel, with the small cards was to make it so that they were informative even if no one clicked on them, and didn't get in the way of the content below. That was my goal.

I do think that putting a bunch of book covers there will not look good - too noisy.

But I think these would make good blog posts! I'm sure that sounds too "bloggy" to you, but we'll make them look good (I haven't spent much time styling them yet).

**Comment by shuchibooksmith** [comment]
Let's keep this on the homepage. Maybe the way to select the books is to use the ones Paul has put up in bmail.
so that would be-
http://www.brooklinebooksmith.com/thisweek/111115.jpg
