### ISSUE TITLE
book cover should hyperlink to the book's page on aba site

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#51]

**Comment by budparr** [comment]
you speaking of the best sellers?

**Comment by shuchibooksmith** [comment]
definitely there, but anywhere there's a cover? i believe on our old events page you could click on the cover and it would take you to the aba listing for the book. we have a buy button on the book descriptions in the web version, but it couldn't hurt to have covers linking to the aba listing too. 

my general thinking is linking to the shopping component whenever possible, until we can figure out a way to make the shopping cart accessible on brooklinebooksmith.com (and have them only jump to aba when they need to pay). what do you think?

**Comment by budparr** [comment]
Well, I'll tell you what I've been thinking. In the bit-more-longer term we need to find a way to get the ABA database that we can use so that we can make a real dent in online sales, but not have to use that site of theirs. 

In the near-term, I was thinking that we could treat the new site as something like a curated book sales space, which would include best sellers, books that have events, staff-picks, gift guides, etc. For those books we could completely bypass the ABA shop, which I don't think is going to generate much for you, and sell right off the new site. There are some really light-weight tools that we can use to make the user experience good enough that people might actually buy off the site. The process of identifying and buying has to be as smooth as possible, and I honestly don't think the ABA stuff is good enough. 

At any rate, that would make the covers link directly to a detail page on the site with a buy button. That's why I haven't linked them to anything yet, but I really just wanted to get the site going and start layering in stuff like this.

**Comment by shuchibooksmith** [comment]
oh interesting, okay. we have one guy who handles all our online sales and special orders (Russ), and he doesn't take too well to learning new systems, so we'd have to figure out how to manage this on our staff side. and we can't really get into that until after the holidays. since we're slow on events for december, and the gift guide has buy buttons, maybe just the bestsellers can link to aba for now? then we can revisit this in january...

**Comment by shuchibooksmith** [comment]
since we're putting up january events now too, the events book covers and weekly bestseller covers should link to ABA listing.
through our e-commerce people can pre-order books (for events).
and though i understand wanting to shift away from the ABA, i don't want to take away the even slim sales we might get from people who want to click on the book and purchase it immediately.

**Comment by budparr** [comment]
Yep. totally with you on that. I'll take care of it.

**Comment by budparr** [comment]
This is set.
