### ISSUE TITLE
High Priority - Get ECommerce Search bar on homepage

### ISSUE THREAD

**Issue by zchyde** [sonnetmedia/brooklinebooksmith.com#53]
So I guess when the site went live on Cyber Monday we lost a lot of sales because there's no way to get to our ecommerce site from the homepage. Bosses are all a flutter. Need this to be a top priority today. Even if just a link in the toolbar for now, but we need something ASAP to cool some heads around here. 

Thank you!

**Comment by zchyde** [comment]
Oh I see now, ther is a link in the toolbar. Can we change the wording from "Search" to "store"?

**Comment by budparr** [comment]
How many sales did you lose? 

At any rate, I put search in the main menu yesterday (issue #47).

**Comment by budparr** [comment]
yes. should be up in a few minutes.

**Comment by zchyde** [comment]
I'm not sure about the sales, but what I think we should change the wording of the "Search" link to "Shop" to make things really intuitive, and in addition to that, I have to ask - is the search box on the home page something you're working on, and if so, when do you think that will be available? These are, er, direct orders, as it were.

**Comment by zchyde** [comment]
oh man you already did it, if I ask you to make it "shop" will you kill me with your own hands?

**Comment by budparr** [comment]
No worries. Well I was going to put a search field in for this site up top, then I got the word to put a link to search for the shop site, so I stopped on the former, because it would be confusing to have two. Of course, if anyone were to search it would most likely be for a book to buy, so having search to the site is good. 

I would be interested to know if the site generates significant sales for you.

**Comment by zchyde** [comment]
From what I am hearing, apparently having a search box in the top of the screen, probably indicating somehow that this is a place people can shop, was a selling point for us. What if we had a search box and a "browse store" somewhere? I think the "shop" link was a quick fix, because of this cyber monday insanity.

**Comment by zchyde** [comment]
We DEFINITELY want a search box, at the top, that people can enter titles into to purchase them. it also needs to be VERY CLEAR that thats what this search box is, probably label it "SEARCH SHOP" or something to that effect

**Comment by zchyde** [comment]
I keep saying "box" but I mean "field"

**Comment by zchyde** [comment]
![screenshot 2015-12-01 10 19 00](https://cloud.githubusercontent.com/assets/15219441/11504906/9f532832-9815-11e5-8759-31e6f5ca5aa1.png)
Something like this maybe?

**Comment by zchyde** [comment]
![template](https://cloud.githubusercontent.com/assets/15219441/11504932/c1d51848-9815-11e5-9b9a-f8c3726191a8.jpg)
Something like this maybe?

**Comment by budparr** [comment]
Should show up now. I'll need to move the follow buttons elsewhere.

**Comment by zchyde** [comment]
oh awesome

**Comment by zchyde** [comment]
![screenshot 2015-12-01 10 42 23](https://cloud.githubusercontent.com/assets/15219441/11505481/8b7b28de-9818-11e5-8eb8-aa9f8e467d2a.png)

heres a thing thats occuring

**Comment by zchyde** [comment]
I wouldn't care about it except if you hit that "search" button again nothing happens

**Comment by budparr** [comment]
I'll look at it. It's problematic having a search button on one site leading to another, and this code is lifted straight from that site.

**Comment by budparr** [comment]
Are you doing anything different when you get that error? I can't seem to replicate the issue, so far.

**Comment by zchyde** [comment]
Its working for Shuchi now but still not me, so I have no idea??? I guess I'm just cursed

**Comment by zchyde** [comment]
I'm just typing a title into the search bar and hitting enter

**Comment by budparr** [comment]
Restart your browser. We have code that tells your browser to hang on to
the web page for a while (to make it load faster) so for those of us
looking at the site a bunch we have to clear things out sometimes. May not
be it, but worth trying.

**Comment by shuchibooksmith** [comment]
This search bar looks great @budparr! Some feedback from our online orders guy, who is keeping the elderly (the customers he frequently deals with) in mind -
1) can we highlight the white search box to make it more prominent and noticeable?
2) underneath the white search box can you add "Shop Online" which links to the aba homepage (so, similar to what you had created in the menu previously, but instead of shopping being in the main menu it will now be an option under the search field)

**Comment by budparr** [comment]
It's good feedback, but let's call that an enhancement and let the dust settle a bit before making more changes like that.

**Comment by shuchibooksmith** [comment]
okay i'll create a new issue for it!

**Comment by budparr** [comment]
I realize you and @zchyde are getting a ton of input from people right now since the site is live. That's all great, and indeed, expected. Just keep in mind that this is the beginning, not the end, of the design process, so take it all in and we'll deal with it methodically and thoughtfully to make the design great; because _ad hoc_ changes never ever make for good design.

**Comment by shuchibooksmith** [comment]
@budparr yeah, you're right. it's already settled a bit over here, which is good. will try to be a bit more balanced about what push through. thank you for being so quick!
