### ISSUE TITLE
Add social media buttons to homepage

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#92]
Noticed our social media buttons aren't on the homepage. I think this was to accommodate the search window? Want to make sure we add them back in. We should also revisit the 'shop online' part of the homepage, which we went overboard with for the holidays but we can probably adjust now...

**Comment by budparr** [comment]
I put them on the bottom right, which is the only "global" place to put them now because we have a lot in the banner. That may actually be good though, because that's an area with clean background on interior pages and the eye likely goes down as one navigates down the page.

I also added  strip of content on the home page with follow buttons and newsletter sign up.
